/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useEffect, useRef, useState } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    球_cell035: THREE.Mesh;
    球_cell056: THREE.Mesh;
    球_cell081: THREE.Mesh;
    球_cell091: THREE.Mesh;
    平面: THREE.Mesh;
    球_cell486: THREE.Mesh;
    球_cell486_1: THREE.Mesh;
    球_cell487: THREE.Mesh;
    球_cell487_1: THREE.Mesh;
    球_cell391: THREE.Mesh;
    球_cell391_1: THREE.Mesh;
    球_cell392: THREE.Mesh;
    球_cell392_1: THREE.Mesh;
    球_cell393: THREE.Mesh;
    球_cell393_1: THREE.Mesh;
    球_cell394: THREE.Mesh;
    球_cell394_1: THREE.Mesh;
    球_cell395: THREE.Mesh;
    球_cell395_1: THREE.Mesh;
    球_cell396: THREE.Mesh;
    球_cell396_1: THREE.Mesh;
    球_cell397: THREE.Mesh;
    球_cell397_1: THREE.Mesh;
    球_cell398: THREE.Mesh;
    球_cell398_1: THREE.Mesh;
    球_cell399: THREE.Mesh;
    球_cell399_1: THREE.Mesh;
    球_cell400: THREE.Mesh;
    球_cell400_1: THREE.Mesh;
    球_cell401: THREE.Mesh;
    球_cell401_1: THREE.Mesh;
    球_cell402: THREE.Mesh;
    球_cell402_1: THREE.Mesh;
    球_cell403: THREE.Mesh;
    球_cell403_1: THREE.Mesh;
    球_cell404: THREE.Mesh;
    球_cell404_1: THREE.Mesh;
    球_cell405: THREE.Mesh;
    球_cell405_1: THREE.Mesh;
    球_cell406: THREE.Mesh;
    球_cell406_1: THREE.Mesh;
    球_cell407: THREE.Mesh;
    球_cell407_1: THREE.Mesh;
    球_cell408: THREE.Mesh;
    球_cell408_1: THREE.Mesh;
    球_cell409: THREE.Mesh;
    球_cell409_1: THREE.Mesh;
    球_cell411: THREE.Mesh;
    球_cell411_1: THREE.Mesh;
    球_cell412: THREE.Mesh;
    球_cell412_1: THREE.Mesh;
    球_cell413: THREE.Mesh;
    球_cell413_1: THREE.Mesh;
    球_cell414: THREE.Mesh;
    球_cell414_1: THREE.Mesh;
    球_cell415: THREE.Mesh;
    球_cell415_1: THREE.Mesh;
    球_cell416: THREE.Mesh;
    球_cell416_1: THREE.Mesh;
    球_cell417: THREE.Mesh;
    球_cell417_1: THREE.Mesh;
    球_cell418: THREE.Mesh;
    球_cell418_1: THREE.Mesh;
    球_cell419: THREE.Mesh;
    球_cell419_1: THREE.Mesh;
    球_cell420: THREE.Mesh;
    球_cell420_1: THREE.Mesh;
    球_cell421: THREE.Mesh;
    球_cell421_1: THREE.Mesh;
    球_cell423: THREE.Mesh;
    球_cell423_1: THREE.Mesh;
    球_cell424: THREE.Mesh;
    球_cell424_1: THREE.Mesh;
    球_cell425: THREE.Mesh;
    球_cell425_1: THREE.Mesh;
    球_cell426: THREE.Mesh;
    球_cell426_1: THREE.Mesh;
    球_cell427: THREE.Mesh;
    球_cell427_1: THREE.Mesh;
    球_cell428: THREE.Mesh;
    球_cell428_1: THREE.Mesh;
    球_cell429: THREE.Mesh;
    球_cell429_1: THREE.Mesh;
    球_cell430: THREE.Mesh;
    球_cell430_1: THREE.Mesh;
    球_cell431: THREE.Mesh;
    球_cell431_1: THREE.Mesh;
    球_cell432: THREE.Mesh;
    球_cell432_1: THREE.Mesh;
    球_cell433: THREE.Mesh;
    球_cell433_1: THREE.Mesh;
    球_cell434: THREE.Mesh;
    球_cell434_1: THREE.Mesh;
    球_cell435: THREE.Mesh;
    球_cell435_1: THREE.Mesh;
    球_cell436: THREE.Mesh;
    球_cell436_1: THREE.Mesh;
    球_cell437: THREE.Mesh;
    球_cell437_1: THREE.Mesh;
    球_cell438: THREE.Mesh;
    球_cell438_1: THREE.Mesh;
    球_cell439: THREE.Mesh;
    球_cell439_1: THREE.Mesh;
    球_cell440: THREE.Mesh;
    球_cell440_1: THREE.Mesh;
    球_cell442: THREE.Mesh;
    球_cell442_1: THREE.Mesh;
    球_cell443: THREE.Mesh;
    球_cell443_1: THREE.Mesh;
    球_cell444: THREE.Mesh;
    球_cell444_1: THREE.Mesh;
    球_cell445: THREE.Mesh;
    球_cell445_1: THREE.Mesh;
    球_cell446: THREE.Mesh;
    球_cell446_1: THREE.Mesh;
    球_cell447: THREE.Mesh;
    球_cell447_1: THREE.Mesh;
    球_cell448: THREE.Mesh;
    球_cell448_1: THREE.Mesh;
    球_cell449: THREE.Mesh;
    球_cell449_1: THREE.Mesh;
    球_cell450: THREE.Mesh;
    球_cell450_1: THREE.Mesh;
    球_cell451: THREE.Mesh;
    球_cell451_1: THREE.Mesh;
    球_cell452: THREE.Mesh;
    球_cell452_1: THREE.Mesh;
    球_cell453: THREE.Mesh;
    球_cell453_1: THREE.Mesh;
    球_cell454: THREE.Mesh;
    球_cell454_1: THREE.Mesh;
    球_cell455: THREE.Mesh;
    球_cell455_1: THREE.Mesh;
    球_cell456: THREE.Mesh;
    球_cell456_1: THREE.Mesh;
    球_cell457: THREE.Mesh;
    球_cell457_1: THREE.Mesh;
    球_cell458: THREE.Mesh;
    球_cell458_1: THREE.Mesh;
    球_cell459: THREE.Mesh;
    球_cell459_1: THREE.Mesh;
    球_cell460: THREE.Mesh;
    球_cell460_1: THREE.Mesh;
    球_cell461: THREE.Mesh;
    球_cell461_1: THREE.Mesh;
    球_cell463: THREE.Mesh;
    球_cell463_1: THREE.Mesh;
    球_cell464: THREE.Mesh;
    球_cell464_1: THREE.Mesh;
    球_cell465: THREE.Mesh;
    球_cell465_1: THREE.Mesh;
    球_cell466: THREE.Mesh;
    球_cell466_1: THREE.Mesh;
    球_cell467: THREE.Mesh;
    球_cell467_1: THREE.Mesh;
    球_cell469: THREE.Mesh;
    球_cell469_1: THREE.Mesh;
    球_cell470: THREE.Mesh;
    球_cell470_1: THREE.Mesh;
  };
  materials: {
    inside: THREE.MeshStandardMaterial;
    rock2: THREE.MeshStandardMaterial;
    rock: THREE.MeshStandardMaterial;
  };
};

type ActionName =
  | "球_cellAction"
  | "球_cell.001Action"
  | "球_cell.002Action"
  | "球_cell.003Action"
  | "球_cell.004Action"
  | "球_cell.005Action"
  | "球_cell.006Action"
  | "球_cell.007Action"
  | "球_cell.008Action"
  | "球_cell.009Action"
  | "球_cell.010Action"
  | "球_cell.011Action"
  | "球_cell.012Action"
  | "球_cell.013Action"
  | "球_cell.014Action"
  | "球_cell.016Action"
  | "球_cell.017Action"
  | "球_cell.018Action"
  | "球_cell.019Action"
  | "球_cell.020Action"
  | "球_cell.021Action"
  | "球_cell.022Action"
  | "球_cell.024Action"
  | "球_cell.025Action"
  | "球_cell.026Action"
  | "球_cell.027Action"
  | "球_cell.028Action"
  | "球_cell.029Action"
  | "球_cell.031Action"
  | "球_cell.032Action"
  | "球_cell.033Action"
  | "球_cell.034Action"
  | "球_cell.035Action"
  | "球_cell.036Action"
  | "球_cell.037Action"
  | "球_cell.038Action"
  | "球_cell.039Action"
  | "球_cell.040Action"
  | "球_cell.041Action"
  | "球_cell.042Action"
  | "球_cell.043Action"
  | "球_cell.044Action"
  | "球_cell.045Action"
  | "球_cell.046Action"
  | "球_cell.047Action"
  | "球_cell.048Action"
  | "球_cell.049Action"
  | "球_cell.051Action"
  | "球_cell.052Action"
  | "球_cell.054Action"
  | "球_cell.055Action"
  | "球_cell.056Action"
  | "球_cell.057Action"
  | "球_cell.058Action"
  | "球_cell.059Action"
  | "球_cell.060Action"
  | "球_cell.061Action"
  | "球_cell.062Action"
  | "球_cell.063Action"
  | "球_cell.065Action"
  | "球_cell.066Action"
  | "球_cell.068Action"
  | "球_cell.069Action"
  | "球_cell.070Action"
  | "球_cell.071Action"
  | "球_cell.072Action"
  | "球_cell.073Action"
  | "球_cell.075Action"
  | "球_cell.076Action"
  | "球_cell.078Action"
  | "球_cell.079Action"
  | "球_cell.080Action"
  | "球_cell.081Action"
  | "球_cell.084Action"
  | "球_cell.087Action"
  | "球_cell.088Action"
  | "球_cell.089Action"
  | "球_cell.090Action"
  | "球_cell.091Action"
  | "球_cell.092Action"
  | "球_cell.093Action";
type GLTFActions = Record<ActionName, THREE.AnimationAction>;

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const group = useRef<THREE.Group>();
  const { nodes, materials, animations } = useGLTF(
    "/assets/models/rock.gltf"
  ) as unknown as GLTFResult;
  const { actions, mixer } = useAnimations(animations, group);
  const [isPlay, setPlay] = useState(false);

  useEffect(() => {
    mixer.timeScale = 3;
    mixer.addEventListener("finished", (e) => {
      e.action.stop();
      setPlay(false);
    });
    Object.keys(actions).forEach((key) => {
      actions[key].setLoop(THREE.LoopPingPong, 2);
    });
  }, []);

  const onClickHandler = (_) => {
    Object.keys(actions).forEach((key) => {
      if (isPlay) actions[key].paused = !actions[key].paused;
      else actions[key].play();
    });
    setPlay(true);
  };

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene" onClick={onClickHandler}>
        <group name="力" position={[0, 2.69, 0]} />
        <mesh
          name="球_cell035"
          castShadow
          receiveShadow
          geometry={nodes.球_cell035.geometry}
          material={materials.inside}
          position={[-0.58, 2.68, 0.25]}
        />
        <mesh
          name="球_cell056"
          castShadow
          receiveShadow
          geometry={nodes.球_cell056.geometry}
          material={materials.inside}
          position={[-0.03, 2.94, -0.25]}
        />
        <mesh
          name="球_cell081"
          castShadow
          receiveShadow
          geometry={nodes.球_cell081.geometry}
          material={materials.inside}
          position={[0.06, 2.62, 0.26]}
        />
        <mesh
          name="球_cell091"
          castShadow
          receiveShadow
          geometry={nodes.球_cell091.geometry}
          material={materials.inside}
          position={[-0.12, 2.26, -0.3]}
        />
        <mesh
          name="平面"
          castShadow
          receiveShadow
          geometry={nodes.平面.geometry}
          material={materials.rock2}
          scale={11.18}
        />
        <group name="球_cell" position={[-0.68, 2.14, 0.38]}>
          <mesh
            name="球_cell486"
            castShadow
            receiveShadow
            geometry={nodes.球_cell486.geometry}
            material={materials.rock}
          />
          <mesh
            name="球_cell486_1"
            castShadow
            receiveShadow
            geometry={nodes.球_cell486_1.geometry}
            material={materials.inside}
          />
        </group>
        <group name="球_cell001" position={[-0.25, 1.9, -0.4]}>
          <mesh
            name="球_cell487"
            castShadow
            receiveShadow
            geometry={nodes.球_cell487.geometry}
            material={materials.rock}
          />
          <mesh
            name="球_cell487_1"
            castShadow
            receiveShadow
            geometry={nodes.球_cell487_1.geometry}
            material={materials.inside}
          />
        </group>
        <group name="球_cell002" position={[-0.39, 3.2, 0.46]}>
          <mesh
            name="球_cell391"
            castShadow
            receiveShadow
            geometry={nodes.球_cell391.geometry}
            material={materials.rock}
          />
          <mesh
            name="球_cell391_1"
            castShadow
            receiveShadow
            geometry={nodes.球_cell391_1.geometry}
            material={materials.inside}
          />
        </group>
        <group name="球_cell003" position={[-0.32, 3.16, -0.67]}>
          <mesh
            name="球_cell392"
            castShadow
            receiveShadow
            geometry={nodes.球_cell392.geometry}
            material={materials.rock}
          />
          <mesh
            name="球_cell392_1"
            castShadow
            receiveShadow
            geometry={nodes.球_cell392_1.geometry}
            material={materials.inside}
          />
        </group>
        <group name="球_cell004" position={[0.95, 2.58, 0.02]}>
          <mesh
            name="球_cell393"
            castShadow
            receiveShadow
            geometry={nodes.球_cell393.geometry}
            material={materials.rock}
          />
          <mesh
            name="球_cell393_1"
            castShadow
            receiveShadow
            geometry={nodes.球_cell393_1.geometry}
            material={materials.inside}
          />
        </group>
        <group name="球_cell005" position={[0.77, 2.65, 0.63]}>
          <mesh
            name="球_cell394"
            castShadow
            receiveShadow
            geometry={nodes.球_cell394.geometry}
            material={materials.rock}
          />
          <mesh
            name="球_cell394_1"
            castShadow
            receiveShadow
            geometry={nodes.球_cell394_1.geometry}
            material={materials.inside}
          />
        </group>
        <group name="球_cell006" position={[0.02, 1.74, 0.01]}>
          <mesh
            name="球_cell395"
            castShadow
            receiveShadow
            geometry={nodes.球_cell395.geometry}
            material={materials.rock}
          />
          <mesh
            name="球_cell395_1"
            castShadow
            receiveShadow
            geometry={nodes.球_cell395_1.geometry}
            material={materials.inside}
          />
        </group>
        <group name="球_cell007" position={[0.8, 2.26, -0.34]}>
          <mesh
            name="球_cell396"
            castShadow
            receiveShadow
            geometry={nodes.球_cell396.geometry}
            material={materials.rock}
          />
          <mesh
            name="球_cell396_1"
            castShadow
            receiveShadow
            geometry={nodes.球_cell396_1.geometry}
            material={materials.inside}
          />
        </group>
        <group name="球_cell008" position={[0.56, 2.92, 0.74]}>
          <mesh
            name="球_cell397"
            castShadow
            receiveShadow
            geometry={nodes.球_cell397.geometry}
            material={materials.rock}
          />
          <mesh
            name="球_cell397_1"
            castShadow
            receiveShadow
            geometry={nodes.球_cell397_1.geometry}
            material={materials.inside}
          />
        </group>
        <group name="球_cell009" position={[-0.66, 3.01, 0.55]}>
          <mesh
            name="球_cell398"
            castShadow
            receiveShadow
            geometry={nodes.球_cell398.geometry}
            material={materials.rock}
          />
          <mesh
            name="球_cell398_1"
            castShadow
            receiveShadow
            geometry={nodes.球_cell398_1.geometry}
            material={materials.inside}
          />
        </group>
        <group name="球_cell010" position={[-0.57, 2.03, -0.02]}>
          <mesh
            name="球_cell399"
            castShadow
            receiveShadow
            geometry={nodes.球_cell399.geometry}
            material={materials.rock}
          />
          <mesh
            name="球_cell399_1"
            castShadow
            receiveShadow
            geometry={nodes.球_cell399_1.geometry}
            material={materials.inside}
          />
        </group>
        <group name="球_cell011" position={[0.66, 2.32, 0.38]}>
          <mesh
            name="球_cell400"
            castShadow
            receiveShadow
            geometry={nodes.球_cell400.geometry}
            material={materials.rock}
          />
          <mesh
            name="球_cell400_1"
            castShadow
            receiveShadow
            geometry={nodes.球_cell400_1.geometry}
            material={materials.inside}
          />
        </group>
        <group name="球_cell012" position={[0.24, 1.81, -0.26]}>
          <mesh
            name="球_cell401"
            castShadow
            receiveShadow
            geometry={nodes.球_cell401.geometry}
            material={materials.rock}
          />
          <mesh
            name="球_cell401_1"
            castShadow
            receiveShadow
            geometry={nodes.球_cell401_1.geometry}
            material={materials.inside}
          />
        </group>
        <group name="球_cell013" position={[-0.12, 2.85, 0.85]}>
          <mesh
            name="球_cell402"
            castShadow
            receiveShadow
            geometry={nodes.球_cell402.geometry}
            material={materials.rock}
          />
          <mesh
            name="球_cell402_1"
            castShadow
            receiveShadow
            geometry={nodes.球_cell402_1.geometry}
            material={materials.inside}
          />
        </group>
        <group name="球_cell014" position={[0.66, 1.99, 0.22]}>
          <mesh
            name="球_cell403"
            castShadow
            receiveShadow
            geometry={nodes.球_cell403.geometry}
            material={materials.rock}
          />
          <mesh
            name="球_cell403_1"
            castShadow
            receiveShadow
            geometry={nodes.球_cell403_1.geometry}
            material={materials.inside}
          />
        </group>
        <group name="球_cell016" position={[0.41, 1.89, 0.26]}>
          <mesh
            name="球_cell404"
            castShadow
            receiveShadow
            geometry={nodes.球_cell404.geometry}
            material={materials.rock}
          />
          <mesh
            name="球_cell404_1"
            castShadow
            receiveShadow
            geometry={nodes.球_cell404_1.geometry}
            material={materials.inside}
          />
        </group>
        <group name="球_cell017" position={[0.41, 2.47, 0.75]}>
          <mesh
            name="球_cell405"
            castShadow
            receiveShadow
            geometry={nodes.球_cell405.geometry}
            material={materials.rock}
          />
          <mesh
            name="球_cell405_1"
            castShadow
            receiveShadow
            geometry={nodes.球_cell405_1.geometry}
            material={materials.inside}
          />
        </group>
        <group name="球_cell018" position={[0.11, 2.82, -0.86]}>
          <mesh
            name="球_cell406"
            castShadow
            receiveShadow
            geometry={nodes.球_cell406.geometry}
            material={materials.rock}
          />
          <mesh
            name="球_cell406_1"
            castShadow
            receiveShadow
            geometry={nodes.球_cell406_1.geometry}
            material={materials.inside}
          />
        </group>
        <group name="球_cell019" position={[0.41, 3.5, -0.09]}>
          <mesh
            name="球_cell407"
            castShadow
            receiveShadow
            geometry={nodes.球_cell407.geometry}
            material={materials.rock}
          />
          <mesh
            name="球_cell407_1"
            castShadow
            receiveShadow
            geometry={nodes.球_cell407_1.geometry}
            material={materials.inside}
          />
        </group>
        <group name="球_cell020" position={[-0.81, 2.6, 0.48]}>
          <mesh
            name="球_cell408"
            castShadow
            receiveShadow
            geometry={nodes.球_cell408.geometry}
            material={materials.rock}
          />
          <mesh
            name="球_cell408_1"
            castShadow
            receiveShadow
            geometry={nodes.球_cell408_1.geometry}
            material={materials.inside}
          />
        </group>
        <group name="球_cell021" position={[-0.26, 1.78, -0.21]}>
          <mesh
            name="球_cell409"
            castShadow
            receiveShadow
            geometry={nodes.球_cell409.geometry}
            material={materials.rock}
          />
          <mesh
            name="球_cell409_1"
            castShadow
            receiveShadow
            geometry={nodes.球_cell409_1.geometry}
            material={materials.inside}
          />
        </group>
        <group name="球_cell022" position={[0.21, 2.17, 0.71]}>
          <mesh
            name="球_cell411"
            castShadow
            receiveShadow
            geometry={nodes.球_cell411.geometry}
            material={materials.rock}
          />
          <mesh
            name="球_cell411_1"
            castShadow
            receiveShadow
            geometry={nodes.球_cell411_1.geometry}
            material={materials.inside}
          />
        </group>
        <group name="球_cell024" position={[-0.59, 1.98, -0.33]}>
          <mesh
            name="球_cell412"
            castShadow
            receiveShadow
            geometry={nodes.球_cell412.geometry}
            material={materials.rock}
          />
          <mesh
            name="球_cell412_1"
            castShadow
            receiveShadow
            geometry={nodes.球_cell412_1.geometry}
            material={materials.inside}
          />
        </group>
        <group name="球_cell025" position={[0.71, 3.13, -0.24]}>
          <mesh
            name="球_cell413"
            castShadow
            receiveShadow
            geometry={nodes.球_cell413.geometry}
            material={materials.rock}
          />
          <mesh
            name="球_cell413_1"
            castShadow
            receiveShadow
            geometry={nodes.球_cell413_1.geometry}
            material={materials.inside}
          />
        </group>
        <group name="球_cell026" position={[0.36, 3.18, 0.4]}>
          <mesh
            name="球_cell414"
            castShadow
            receiveShadow
            geometry={nodes.球_cell414.geometry}
            material={materials.rock}
          />
          <mesh
            name="球_cell414_1"
            castShadow
            receiveShadow
            geometry={nodes.球_cell414_1.geometry}
            material={materials.inside}
          />
        </group>
        <group name="球_cell027" position={[0.34, 3.3, -0.5]}>
          <mesh
            name="球_cell415"
            castShadow
            receiveShadow
            geometry={nodes.球_cell415.geometry}
            material={materials.rock}
          />
          <mesh
            name="球_cell415_1"
            castShadow
            receiveShadow
            geometry={nodes.球_cell415_1.geometry}
            material={materials.inside}
          />
        </group>
        <group name="球_cell028" position={[-0.43, 3.55, -0.04]}>
          <mesh
            name="球_cell416"
            castShadow
            receiveShadow
            geometry={nodes.球_cell416.geometry}
            material={materials.rock}
          />
          <mesh
            name="球_cell416_1"
            castShadow
            receiveShadow
            geometry={nodes.球_cell416_1.geometry}
            material={materials.inside}
          />
        </group>
        <group name="球_cell029" position={[-0.35, 2.22, -0.72]}>
          <mesh
            name="球_cell417"
            castShadow
            receiveShadow
            geometry={nodes.球_cell417.geometry}
            material={materials.rock}
          />
          <mesh
            name="球_cell417_1"
            castShadow
            receiveShadow
            geometry={nodes.球_cell417_1.geometry}
            material={materials.inside}
          />
        </group>
        <group name="球_cell031" position={[0, 3.53, -0.38]}>
          <mesh
            name="球_cell418"
            castShadow
            receiveShadow
            geometry={nodes.球_cell418.geometry}
            material={materials.rock}
          />
          <mesh
            name="球_cell418_1"
            castShadow
            receiveShadow
            geometry={nodes.球_cell418_1.geometry}
            material={materials.inside}
          />
        </group>
        <group name="球_cell032" position={[0.15, 1.89, -0.51]}>
          <mesh
            name="球_cell419"
            castShadow
            receiveShadow
            geometry={nodes.球_cell419.geometry}
            material={materials.rock}
          />
          <mesh
            name="球_cell419_1"
            castShadow
            receiveShadow
            geometry={nodes.球_cell419_1.geometry}
            material={materials.inside}
          />
        </group>
        <group name="球_cell033" position={[0.29, 1.95, 0.01]}>
          <mesh
            name="球_cell420"
            castShadow
            receiveShadow
            geometry={nodes.球_cell420.geometry}
            material={materials.rock}
          />
          <mesh
            name="球_cell420_1"
            castShadow
            receiveShadow
            geometry={nodes.球_cell420_1.geometry}
            material={materials.inside}
          />
        </group>
        <group name="球_cell034" position={[-0.33, 1.8, 0.21]}>
          <mesh
            name="球_cell421"
            castShadow
            receiveShadow
            geometry={nodes.球_cell421.geometry}
            material={materials.rock}
          />
          <mesh
            name="球_cell421_1"
            castShadow
            receiveShadow
            geometry={nodes.球_cell421_1.geometry}
            material={materials.inside}
          />
        </group>
        <group name="球_cell036" position={[-0.02, 1.98, 0.47]}>
          <mesh
            name="球_cell423"
            castShadow
            receiveShadow
            geometry={nodes.球_cell423.geometry}
            material={materials.rock}
          />
          <mesh
            name="球_cell423_1"
            castShadow
            receiveShadow
            geometry={nodes.球_cell423_1.geometry}
            material={materials.inside}
          />
        </group>
        <group name="球_cell037" position={[-0.73, 2.96, -0.47]}>
          <mesh
            name="球_cell424"
            castShadow
            receiveShadow
            geometry={nodes.球_cell424.geometry}
            material={materials.rock}
          />
          <mesh
            name="球_cell424_1"
            castShadow
            receiveShadow
            geometry={nodes.球_cell424_1.geometry}
            material={materials.inside}
          />
        </group>
        <group name="球_cell038" position={[-0.43, 1.97, -0.51]}>
          <mesh
            name="球_cell425"
            castShadow
            receiveShadow
            geometry={nodes.球_cell425.geometry}
            material={materials.rock}
          />
          <mesh
            name="球_cell425_1"
            castShadow
            receiveShadow
            geometry={nodes.球_cell425_1.geometry}
            material={materials.inside}
          />
        </group>
        <group name="球_cell039" position={[-0.61, 2.54, 0.7]}>
          <mesh
            name="球_cell426"
            castShadow
            receiveShadow
            geometry={nodes.球_cell426.geometry}
            material={materials.rock}
          />
          <mesh
            name="球_cell426_1"
            castShadow
            receiveShadow
            geometry={nodes.球_cell426_1.geometry}
            material={materials.inside}
          />
        </group>
        <group name="球_cell040" position={[0.88, 2.66, 0.39]}>
          <mesh
            name="球_cell427"
            castShadow
            receiveShadow
            geometry={nodes.球_cell427.geometry}
            material={materials.rock}
          />
          <mesh
            name="球_cell427_1"
            castShadow
            receiveShadow
            geometry={nodes.球_cell427_1.geometry}
            material={materials.inside}
          />
        </group>
        <group name="球_cell041" position={[0.51, 2.04, 0.56]}>
          <mesh
            name="球_cell428"
            castShadow
            receiveShadow
            geometry={nodes.球_cell428.geometry}
            material={materials.rock}
          />
          <mesh
            name="球_cell428_1"
            castShadow
            receiveShadow
            geometry={nodes.球_cell428_1.geometry}
            material={materials.inside}
          />
        </group>
        <group name="球_cell042" position={[0.01, 3.52, 0.11]}>
          <mesh
            name="球_cell429"
            castShadow
            receiveShadow
            geometry={nodes.球_cell429.geometry}
            material={materials.rock}
          />
          <mesh
            name="球_cell429_1"
            castShadow
            receiveShadow
            geometry={nodes.球_cell429_1.geometry}
            material={materials.inside}
          />
        </group>
        <group name="球_cell043" position={[-0.31, 3.44, -0.37]}>
          <mesh
            name="球_cell430"
            castShadow
            receiveShadow
            geometry={nodes.球_cell430.geometry}
            material={materials.rock}
          />
          <mesh
            name="球_cell430_1"
            castShadow
            receiveShadow
            geometry={nodes.球_cell430_1.geometry}
            material={materials.inside}
          />
        </group>
        <group name="球_cell044" position={[0.66, 2.87, -0.67]}>
          <mesh
            name="球_cell431"
            castShadow
            receiveShadow
            geometry={nodes.球_cell431.geometry}
            material={materials.rock}
          />
          <mesh
            name="球_cell431_1"
            castShadow
            receiveShadow
            geometry={nodes.球_cell431_1.geometry}
            material={materials.inside}
          />
        </group>
        <group name="球_cell045" position={[0.39, 2.39, -0.76]}>
          <mesh
            name="球_cell432"
            castShadow
            receiveShadow
            geometry={nodes.球_cell432.geometry}
            material={materials.rock}
          />
          <mesh
            name="球_cell432_1"
            castShadow
            receiveShadow
            geometry={nodes.球_cell432_1.geometry}
            material={materials.inside}
          />
        </group>
        <group name="球_cell046" position={[0.62, 3.36, 0.31]}>
          <mesh
            name="球_cell433"
            castShadow
            receiveShadow
            geometry={nodes.球_cell433.geometry}
            material={materials.rock}
          />
          <mesh
            name="球_cell433_1"
            castShadow
            receiveShadow
            geometry={nodes.球_cell433_1.geometry}
            material={materials.inside}
          />
        </group>
        <group name="球_cell047" position={[-0.39, 2.1, 0.43]}>
          <mesh
            name="球_cell434"
            castShadow
            receiveShadow
            geometry={nodes.球_cell434.geometry}
            material={materials.rock}
          />
          <mesh
            name="球_cell434_1"
            castShadow
            receiveShadow
            geometry={nodes.球_cell434_1.geometry}
            material={materials.inside}
          />
        </group>
        <group name="球_cell048" position={[-0.62, 2.4, -0.39]}>
          <mesh
            name="球_cell435"
            castShadow
            receiveShadow
            geometry={nodes.球_cell435.geometry}
            material={materials.rock}
          />
          <mesh
            name="球_cell435_1"
            castShadow
            receiveShadow
            geometry={nodes.球_cell435_1.geometry}
            material={materials.inside}
          />
        </group>
        <group name="球_cell049" position={[0.36, 3.49, 0.28]}>
          <mesh
            name="球_cell436"
            castShadow
            receiveShadow
            geometry={nodes.球_cell436.geometry}
            material={materials.rock}
          />
          <mesh
            name="球_cell436_1"
            castShadow
            receiveShadow
            geometry={nodes.球_cell436_1.geometry}
            material={materials.inside}
          />
        </group>
        <group name="球_cell051" position={[-0.63, 3.19, -0.15]}>
          <mesh
            name="球_cell437"
            castShadow
            receiveShadow
            geometry={nodes.球_cell437.geometry}
            material={materials.rock}
          />
          <mesh
            name="球_cell437_1"
            castShadow
            receiveShadow
            geometry={nodes.球_cell437_1.geometry}
            material={materials.inside}
          />
        </group>
        <group name="球_cell052" position={[0.37, 2.7, 0.81]}>
          <mesh
            name="球_cell438"
            castShadow
            receiveShadow
            geometry={nodes.球_cell438.geometry}
            material={materials.rock}
          />
          <mesh
            name="球_cell438_1"
            castShadow
            receiveShadow
            geometry={nodes.球_cell438_1.geometry}
            material={materials.inside}
          />
        </group>
        <group name="球_cell054" position={[0.53, 3.39, 0.4]}>
          <mesh
            name="球_cell439"
            castShadow
            receiveShadow
            geometry={nodes.球_cell439.geometry}
            material={materials.rock}
          />
          <mesh
            name="球_cell439_1"
            castShadow
            receiveShadow
            geometry={nodes.球_cell439_1.geometry}
            material={materials.inside}
          />
        </group>
        <group name="球_cell055" position={[0.4, 2.43, -0.41]}>
          <mesh
            name="球_cell440"
            castShadow
            receiveShadow
            geometry={nodes.球_cell440.geometry}
            material={materials.rock}
          />
          <mesh
            name="球_cell440_1"
            castShadow
            receiveShadow
            geometry={nodes.球_cell440_1.geometry}
            material={materials.inside}
          />
        </group>
        <group name="球_cell057" position={[-0.75, 3.19, 0.14]}>
          <mesh
            name="球_cell442"
            castShadow
            receiveShadow
            geometry={nodes.球_cell442.geometry}
            material={materials.rock}
          />
          <mesh
            name="球_cell442_1"
            castShadow
            receiveShadow
            geometry={nodes.球_cell442_1.geometry}
            material={materials.inside}
          />
        </group>
        <group name="球_cell058" position={[0.2, 3.61, -0.15]}>
          <mesh
            name="球_cell443"
            castShadow
            receiveShadow
            geometry={nodes.球_cell443.geometry}
            material={materials.rock}
          />
          <mesh
            name="球_cell443_1"
            castShadow
            receiveShadow
            geometry={nodes.球_cell443_1.geometry}
            material={materials.inside}
          />
        </group>
        <group name="球_cell059" position={[-0.47, 1.8, -0.07]}>
          <mesh
            name="球_cell444"
            castShadow
            receiveShadow
            geometry={nodes.球_cell444.geometry}
            material={materials.rock}
          />
          <mesh
            name="球_cell444_1"
            castShadow
            receiveShadow
            geometry={nodes.球_cell444_1.geometry}
            material={materials.inside}
          />
        </group>
        <group name="球_cell060" position={[-0.02, 3.48, 0.47]}>
          <mesh
            name="球_cell445"
            castShadow
            receiveShadow
            geometry={nodes.球_cell445.geometry}
            material={materials.rock}
          />
          <mesh
            name="球_cell445_1"
            castShadow
            receiveShadow
            geometry={nodes.球_cell445_1.geometry}
            material={materials.inside}
          />
        </group>
        <group name="球_cell061" position={[0.79, 2.71, 0.58]}>
          <mesh
            name="球_cell446"
            castShadow
            receiveShadow
            geometry={nodes.球_cell446.geometry}
            material={materials.rock}
          />
          <mesh
            name="球_cell446_1"
            castShadow
            receiveShadow
            geometry={nodes.球_cell446_1.geometry}
            material={materials.inside}
          />
        </group>
        <group name="球_cell062" position={[0.79, 2.67, -0.24]}>
          <mesh
            name="球_cell447"
            castShadow
            receiveShadow
            geometry={nodes.球_cell447.geometry}
            material={materials.rock}
          />
          <mesh
            name="球_cell447_1"
            castShadow
            receiveShadow
            geometry={nodes.球_cell447_1.geometry}
            material={materials.inside}
          />
        </group>
        <group name="球_cell063" position={[-0.91, 2.8, 0.09]}>
          <mesh
            name="球_cell448"
            castShadow
            receiveShadow
            geometry={nodes.球_cell448.geometry}
            material={materials.rock}
          />
          <mesh
            name="球_cell448_1"
            castShadow
            receiveShadow
            geometry={nodes.球_cell448_1.geometry}
            material={materials.inside}
          />
        </group>
        <group name="球_cell065" position={[-0.09, 1.73, -0.12]}>
          <mesh
            name="球_cell449"
            castShadow
            receiveShadow
            geometry={nodes.球_cell449.geometry}
            material={materials.rock}
          />
          <mesh
            name="球_cell449_1"
            castShadow
            receiveShadow
            geometry={nodes.球_cell449_1.geometry}
            material={materials.inside}
          />
        </group>
        <group name="球_cell066" position={[-0.24, 1.8, 0.42]}>
          <mesh
            name="球_cell450"
            castShadow
            receiveShadow
            geometry={nodes.球_cell450.geometry}
            material={materials.rock}
          />
          <mesh
            name="球_cell450_1"
            castShadow
            receiveShadow
            geometry={nodes.球_cell450_1.geometry}
            material={materials.inside}
          />
        </group>
        <group name="球_cell068" position={[0.56, 3.19, 0.54]}>
          <mesh
            name="球_cell451"
            castShadow
            receiveShadow
            geometry={nodes.球_cell451.geometry}
            material={materials.rock}
          />
          <mesh
            name="球_cell451_1"
            castShadow
            receiveShadow
            geometry={nodes.球_cell451_1.geometry}
            material={materials.inside}
          />
        </group>
        <group name="球_cell069" position={[0.09, 1.73, 0.21]}>
          <mesh
            name="球_cell452"
            castShadow
            receiveShadow
            geometry={nodes.球_cell452.geometry}
            material={materials.rock}
          />
          <mesh
            name="球_cell452_1"
            castShadow
            receiveShadow
            geometry={nodes.球_cell452_1.geometry}
            material={materials.inside}
          />
        </group>
        <group name="球_cell070" position={[-0.32, 2.48, 0.8]}>
          <mesh
            name="球_cell453"
            castShadow
            receiveShadow
            geometry={nodes.球_cell453.geometry}
            material={materials.rock}
          />
          <mesh
            name="球_cell453_1"
            castShadow
            receiveShadow
            geometry={nodes.球_cell453_1.geometry}
            material={materials.inside}
          />
        </group>
        <group name="球_cell071" position={[0.77, 2.94, 0.32]}>
          <mesh
            name="球_cell454"
            castShadow
            receiveShadow
            geometry={nodes.球_cell454.geometry}
            material={materials.rock}
          />
          <mesh
            name="球_cell454_1"
            castShadow
            receiveShadow
            geometry={nodes.球_cell454_1.geometry}
            material={materials.inside}
          />
        </group>
        <group name="球_cell072" position={[-0.4, 3.51, 0.17]}>
          <mesh
            name="球_cell455"
            castShadow
            receiveShadow
            geometry={nodes.球_cell455.geometry}
            material={materials.rock}
          />
          <mesh
            name="球_cell455_1"
            castShadow
            receiveShadow
            geometry={nodes.球_cell455_1.geometry}
            material={materials.inside}
          />
        </group>
        <group name="球_cell073" position={[-0.37, 2.78, -0.81]}>
          <mesh
            name="球_cell456"
            castShadow
            receiveShadow
            geometry={nodes.球_cell456.geometry}
            material={materials.rock}
          />
          <mesh
            name="球_cell456_1"
            castShadow
            receiveShadow
            geometry={nodes.球_cell456_1.geometry}
            material={materials.inside}
          />
        </group>
        <group name="球_cell075" position={[0.67, 3.34, 0.1]}>
          <mesh
            name="球_cell457"
            castShadow
            receiveShadow
            geometry={nodes.球_cell457.geometry}
            material={materials.rock}
          />
          <mesh
            name="球_cell457_1"
            castShadow
            receiveShadow
            geometry={nodes.球_cell457_1.geometry}
            material={materials.inside}
          />
        </group>
        <group name="球_cell076" position={[-0.89, 2.45, -0.09]}>
          <mesh
            name="球_cell458"
            castShadow
            receiveShadow
            geometry={nodes.球_cell458.geometry}
            material={materials.rock}
          />
          <mesh
            name="球_cell458_1"
            castShadow
            receiveShadow
            geometry={nodes.球_cell458_1.geometry}
            material={materials.inside}
          />
        </group>
        <group name="球_cell078" position={[-0.78, 2.61, -0.57]}>
          <mesh
            name="球_cell459"
            castShadow
            receiveShadow
            geometry={nodes.球_cell459.geometry}
            material={materials.rock}
          />
          <mesh
            name="球_cell459_1"
            castShadow
            receiveShadow
            geometry={nodes.球_cell459_1.geometry}
            material={materials.inside}
          />
        </group>
        <group name="球_cell079" position={[0.62, 2.02, -0.2]}>
          <mesh
            name="球_cell460"
            castShadow
            receiveShadow
            geometry={nodes.球_cell460.geometry}
            material={materials.rock}
          />
          <mesh
            name="球_cell460_1"
            castShadow
            receiveShadow
            geometry={nodes.球_cell460_1.geometry}
            material={materials.inside}
          />
        </group>
        <group name="球_cell080" position={[0.1, 2.16, -0.78]}>
          <mesh
            name="球_cell461"
            castShadow
            receiveShadow
            geometry={nodes.球_cell461.geometry}
            material={materials.rock}
          />
          <mesh
            name="球_cell461_1"
            castShadow
            receiveShadow
            geometry={nodes.球_cell461_1.geometry}
            material={materials.inside}
          />
        </group>
        <group name="球_cell084" position={[0.18, 3.14, 0.77]}>
          <mesh
            name="球_cell463"
            castShadow
            receiveShadow
            geometry={nodes.球_cell463.geometry}
            material={materials.rock}
          />
          <mesh
            name="球_cell463_1"
            castShadow
            receiveShadow
            geometry={nodes.球_cell463_1.geometry}
            material={materials.inside}
          />
        </group>
        <group name="球_cell087" position={[0.35, 1.73, -0.06]}>
          <mesh
            name="球_cell464"
            castShadow
            receiveShadow
            geometry={nodes.球_cell464.geometry}
            material={materials.rock}
          />
          <mesh
            name="球_cell464_1"
            castShadow
            receiveShadow
            geometry={nodes.球_cell464_1.geometry}
            material={materials.inside}
          />
        </group>
        <group name="球_cell088" position={[0.34, 1.92, 0.53]}>
          <mesh
            name="球_cell465"
            castShadow
            receiveShadow
            geometry={nodes.球_cell465.geometry}
            material={materials.rock}
          />
          <mesh
            name="球_cell465_1"
            castShadow
            receiveShadow
            geometry={nodes.球_cell465_1.geometry}
            material={materials.inside}
          />
        </group>
        <group name="球_cell089" position={[0.03, 3.27, -0.77]}>
          <mesh
            name="球_cell466"
            castShadow
            receiveShadow
            geometry={nodes.球_cell466.geometry}
            material={materials.rock}
          />
          <mesh
            name="球_cell466_1"
            castShadow
            receiveShadow
            geometry={nodes.球_cell466_1.geometry}
            material={materials.inside}
          />
        </group>
        <group name="球_cell090" position={[0.86, 2.35, 0.07]}>
          <mesh
            name="球_cell467"
            castShadow
            receiveShadow
            geometry={nodes.球_cell467.geometry}
            material={materials.rock}
          />
          <mesh
            name="球_cell467_1"
            castShadow
            receiveShadow
            geometry={nodes.球_cell467_1.geometry}
            material={materials.inside}
          />
        </group>
        <group name="球_cell092" position={[-0.07, 3.61, -0.07]}>
          <mesh
            name="球_cell469"
            castShadow
            receiveShadow
            geometry={nodes.球_cell469.geometry}
            material={materials.rock}
          />
          <mesh
            name="球_cell469_1"
            castShadow
            receiveShadow
            geometry={nodes.球_cell469_1.geometry}
            material={materials.inside}
          />
        </group>
        <group name="球_cell093" position={[-0.11, 3.27, 0.73]}>
          <mesh
            name="球_cell470"
            castShadow
            receiveShadow
            geometry={nodes.球_cell470.geometry}
            material={materials.rock}
          />
          <mesh
            name="球_cell470_1"
            castShadow
            receiveShadow
            geometry={nodes.球_cell470_1.geometry}
            material={materials.inside}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/assets/models/rock.gltf");
